name: Collect Seoul Population Data

on:
  schedule:
    - cron: '0 * * * *'  # 매 정각마다 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Data Collector
        run: python popularity/data_collector_v2.py

      - name: Commit
        run: |
          git config --global user.email "jaeuk520@naver.com"
          git config --global user.name "jaeuk520"
          git checkout feature/data_collector
          git add ./popularity/data/*
          git commit -m "feat: 실시간 인구 데이터 수집 $(date +'%Y-%m-%d %H:%M')"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
            branch: feature/data_collector
            github_token: ${{secrets.GITHUB_TOKEN}}
