name: Test

on:
  schedule:
    - cron: '0 * * * *'  # 매 정각마다 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run a script
      run: echo "Hello, world!"
